### PR TITLE
Update info.rkt to add category

### PR DESCRIPTION
**Pull request by spdegabrielle**
Update info.rkt scribblings parameter to add "DrRacket Plugin" category.

### CODE REVIEW

**Comment by Metaxal** [comment]
Hey Stephen, I'm not entirely clear what this change is supposed to be doing. Can you clarify?

**Comment by spdegabrielle** [comment]
Adds quickscript to the DrRacket Plugins category on docs.racket-lang.org 
via the third parameter in scribblings https://docs.racket-lang.org/raco/setup-info.html#%28idx._%28gentag._16._%28lib._scribblings%2Fraco%2Fraco..scrbl%29%29%29

**Comment by Metaxal** [comment]
This commit doesn't seem to work:
```
raco-local: WARNING: bad 'scribblings info: '(("scribblings/quickscript.scrbl" () (tool "DrRacket Plugin") "quickscript")) 
```
I'm not sure what was wrong with the previous state though? Quickscript was already in the Tools section.

**Comment by spdegabrielle** [comment]
The goal is to make the top level of docs.racket-lang.org
 
 i made a couple of dozen PR’s in different packages - unfortunately yours is one of two where I made a mistake.

i’ve fixed the PR but but you may disagree with my categorisation.

**Comment by spdegabrielle** [comment]
since I posted this one of my PR’s has been accepted:

https://github.com/racket/racket/pull/4687
Superseding the change

**Comment by Metaxal** [comment]
@sorawee mentions the category should be "DrRacket Plugins" (plural) instead. WDYT?

**Comment by spdegabrielle** [comment]
The symbol in singular maps to the heading in plural 
  `  (drracket-plugin "DrRacket Plugins") `

this is the convention
in pkgs/racket-index/scribblings/main/config.rkt

**Comment by sorawee** [comment]
Actually, one thing that I forgot to think about is backward compatibility _for Quickscript_ w.r.t. the `drracket-plugin` symbol. `'drracket-plugin` will work fine for Racket 8.10, but it's unclear what will happen in prior versions. Can you test?

**Comment by spdegabrielle** [comment]
I've given https://pkgd.racket-lang.org/pkgn/package/Coroutines a non-existent category symbol.
We will see how it goes.

```scheme
(define scribblings
  (list (list "coroutines.scrbl"
              (list 'multi-page)
              (list 'concurrency)
              "coroutines")))
```

**Comment by Metaxal** [comment]
On Racket 8.9.0.5, this is how it appears:
image
I guess there's an automatic camel case based on the symbol? :thinking:

**Comment by sorawee** [comment]
@Metaxal it looks like you are testing against the first commit of this PR, but the PR has since been updated to use a symbol instead. Can you try again?

**Comment by Metaxal** [comment]
This is weird. My quickscript/info.rkt says:
```
(define scribblings '(("scribblings/quickscript.scrbl" () (drracket-plugin) "quickscript")))
```
so I tried to change it to 
```
(define scribblings '(("scribblings/quickscript.scrbl" () (drracket-pluginnnn) "quickscript")))
```
but this had no effect. Tried reloading the page and ignoring the cache, same thing. There may be something wrong with my Racket install.

**Comment by Metaxal** [comment]
Apparently if the category is wrong, it just puts the docs back into "Misc", but since I can't manage to trigger the update of the top page it's complicated to test.

**Comment by rfindler** [comment]
It should work to throw away the generated directory that contains the html
page. (And there may be a bug to fix in scribble somewhere.)

Robby

**Comment by Metaxal** [comment]
Ah, finally! Deleting index.html and `raco setup --doc-index` works, thanks @rfindler.

**Pull request merged**
