### PR TITLE
add missing inner and super calls to augmented and overriden methods

### LINKED ISSUE #77: overridden and augmented methods need to call inner / super
It looks like [this issue](https://github.com/racket/htdp/issues/209) is caused because the `on-close` method defined in tool.rkt doesn't call `inner`.

### PR DESCRIPTION
**Pull request by rfindler**
closes #77

### CODE REVIEW

**Comment by Metaxal** [comment]
Thanks for the fix! 

Just checking: since these calls can be either before or after the body (and in the examples in the docs they are placed after the body), are you positive they are at the right place? 

As a side note, to be honest, the docs for `augment` could be clearer about this. I could only find:
> When a method is declared with [pubment](https://docs.racket-lang.org/reference/createclass.html#%28form._%28%28lib._racket%2Fprivate%2Fclass-internal..rkt%29._pubment%29%29), [augment](https://docs.racket-lang.org/reference/createclass.html#%28form._%28%28lib._racket%2Fprivate%2Fclass-internal..rkt%29._augment%29%29), or [overment](https://docs.racket-lang.org/reference/createclass.html#%28form._%28%28lib._racket%2Fprivate%2Fclass-internal..rkt%29._overment%29%29), then a subclass augmenting method can be called using the [inner](https://docs.racket-lang.org/reference/createclass.html#%28form._%28%28lib._racket%2Fprivate%2Fclass-internal..rkt%29._inner%29%29) form.

which doesn't really look like an imperative.

**Comment by Metaxal** [comment]
I'll assume you considered the order carefully. Let me know otherwise.

Is there a test I can add to my test cases?

**Comment by rfindler** [comment]
> Just checking: since these calls can be either before or after the body (and in the examples in the docs they are placed after the body), are you positive they are at the right place?

I think it probably doesn't matter if they go before or after the calls to `queue-callback`. I suppose an inner call might raise an error and, in that case, you may or may not want to trigger quickscripts, but absent something along these lines, both are probably okay.

> As a side note, to be honest, the docs for `augment` could be clearer about this. I could only find:
> 
> > When a method is declared with [pubment](https://docs.racket-lang.org/reference/createclass.html#%28form._%28%28lib._racket%2Fprivate%2Fclass-internal..rkt%29._pubment%29%29), [augment](https://docs.racket-lang.org/reference/createclass.html#%28form._%28%28lib._racket%2Fprivate%2Fclass-internal..rkt%29._augment%29%29), or [overment](https://docs.racket-lang.org/reference/createclass.html#%28form._%28%28lib._racket%2Fprivate%2Fclass-internal..rkt%29._overment%29%29), then a subclass augmenting method can be called using the [inner](https://docs.racket-lang.org/reference/createclass.html#%28form._%28%28lib._racket%2Fprivate%2Fclass-internal..rkt%29._inner%29%29) form.
> 
> which doesn't really look like an imperative.

It isn't required to call `inner` in general. It is just that these methods are intended to be observers and are not intended to stop other observers, which is why calling `inner` is needed in this case. That is, it may be the case that some augmentable method wants to control what subclasses can see and so it would choose not to call `inner` in some (or all) situations. Here, however, that's not what we want.

**Comment by rfindler** [comment]
> Is there a test I can add to my test cases?

I'm not seeing something obvious that can be added to tools. It may make sense for there to be a DrRacket test, however, that checks to make sure all tools actually invoke inner/super correctly by adding mixins at the top/bottom and then doing some action and then checking that the right methods got invoked. That'd have found this when the change was first made, which would have made it easier to figure out what was going wrong [back in the original pr](https://github.com/racket/htdp/issues/209)!

**Comment by Metaxal** [comment]
Ok, I see, thanks for the explanations!

**Pull request merged**
