### PR TITLE
docs: stop recommending add-third-party-script-directory!

### PR DESCRIPTION
**Pull request by LiberalArtist**
I think this should be merged for the 8.12 release even if the fix for https://github.com/Metaxal/quickscript/issues/73 isn't ready in time, or if we decide to hold it for more testing.

### CODE REVIEW

**Comment by LiberalArtist** [comment]
Thanks! Is there another step that needs to be done to cherry-pick this for 8.12? (Assuming you agree, @Metaxal, but that was the point of splitting this off from https://github.com/Metaxal/quickscript/pull/81.)

cc @jbclements

**Comment by rfindler** [comment]
Unless there is a pressing bugfix here (I've lost track -- is there?) I think we should try to merge to regular master and see how it goes with internal use for one release cycle.

**Comment by LiberalArtist** [comment]
This commit, merged as 570bc284e29e5b904c58d746ea8646105a81b552, just comments out the part of the documentation that currently recommends that third-party packages use `add-third-party-script-directory!` under `begin-for-syntax`, since we have determined that the strategy:

1. Breaks some environments; and
2. Doesn't reliably work, even when it doesn't raise and warnings or errors.

That documentation change is all I propose cherry-picking for 8.12.

My attempt at providing a mechanism that *does* reliably work is over in https://github.com/Metaxal/quickscript/pull/81, and I agree that it seems better to have a release cycle to confirm that whatever is eventually merged does work out well in practice.

I believe @Metaxal's https://github.com/Metaxal/quickscript/commit/837921c7623b7156b6fb0208b1cd3027caa245fc last month already fixed the bug in 8.11[.1] that affected Debian, Guix, Nix, and probably others, and I'll plan to build a release candidate to make sure.

**Comment by rfindler** [comment]
Oh, shoot! I somehow thought this was the other pull request. And yes, this one does need to be explicitly merged, I see. I don't see who is the release manager for this repo, however. But yes, let's cherry-pick 1c44fd5bf1786139ebeefce7f1f312b94a0218e7 to the release branch!

**Comment by Metaxal** [comment]
I agree that we should probably use https://github.com/Metaxal/quickscript/commit/1c44fd5bf1786139ebeefce7f1f312b94a0218e7 for 8.12, so as to give us more time to test the new design.

**Comment by jbclements** [comment]
@Metaxal you're the release manager for the quickscript repos, you should be able to merge this for the release using the status page at 

https://pre-release.racket-lang.org/status/?repo=Metaxal/quickscript

Let me know if you have any questions!

**Comment by Metaxal** [comment]
Oh cool, I didn't know there's an interface to cherry pick!

**Comment by Metaxal** [comment]
Done!

**Pull request merged**
